Migrate TC: VHDX-RESIZE-TO-BIGGER512
santoshx/LISAv2 pull request #1
Opened 2018-10-11 12:05 UTC by santoshx

2018-10-11 14:07 UTC, santoshx commented
$ cat TestResults/2018-11-10-19-16-51-6878/Logs.txt
10/11/2018 13:46:51 : [INFO ] Created LogDir: .\TestResults\2018-11-10-19-16-51-687810/11/2018 13:46:51 : [INFO ] 7za.exe file found in Tools folder.
10/11/2018 13:46:51 : [INFO ] dos2unix.exe file found in Tools folder.
10/11/2018 13:46:51 : [INFO ] gawk file found in Tools folder.
10/11/2018 13:46:51 : [INFO ] jq file found in Tools folder.
10/11/2018 13:46:51 : [INFO ] plink.exe file found in Tools folder.
10/11/2018 13:46:51 : [INFO ] pscp.exe file found in Tools folder.
10/11/2018 13:46:51 : [INFO ] kvp_client32 file found in Tools folder.
10/11/2018 13:46:51 : [INFO ] kvp_client64 file found in Tools folder.
10/11/2018 13:46:51 : [INFO ] nc.exe file found in Tools folder.
10/11/2018 13:46:51 : [INFO ] Test parameters have been validated successfully. Continue running the test.
10/11/2018 13:46:51 : [INFO ] Read Test Location from GlobalConfiguration.Global.HyperV.Hosts.ChildNodes[0].ServerName
10/11/2018 13:46:51 : [INFO ] Validating XML Files from D:\Santosh\GitHub\LISAv2 folder recursively...
10/11/2018 13:46:52 : [INFO ] Collected VHDX-RESIZE-TO-BIGGER512
10/11/2018 13:46:52 : [INFO ] Auto created D:\Santosh\GitHub\LISAv2\TestConfiguration.xml validated successfully.
10/11/2018 13:46:52 : [INFO ] .\AutomationManager.ps1 -xmlConfigFile 'D:\Santosh\GitHub\LISAv2\TestConfiguration.xml' -cycleName 'TC-33821' -RGIdentifier 'santoshx' -runtests -UseAzureResourceManager
10/11/2018 13:46:52 : [INFO ] '.\TestResults\2018-11-10-19-16-51-6878' saved to .\report\lastLogDirectory.txt
10/11/2018 13:46:52 : [INFO ] Info : AzureAutomationManager.ps1 - LIS on Azure Automation
10/11/2018 13:46:52 : [INFO ] Info : Created test results directory:.\TestResults\2018-11-10-19-16-51-6878
10/11/2018 13:46:52 : [INFO ] Info : Using config file D:\Santosh\GitHub\LISAv2\TestConfiguration.xml
10/11/2018 13:46:52 : [INFO ] HyperV Host            : localhost
10/11/2018 13:46:52 : [INFO ] Source VHD Path        : D:\VHDs\
10/11/2018 13:46:52 : [INFO ] Destination VHD Path   : VHDs_Destination_Path
10/11/2018 13:46:52 : [INFO ] Starting the Cycle - TC-33821
10/11/2018 13:46:52 : [INFO ] ARMImage name -  :  :  :
10/11/2018 13:46:52 : [INFO ] Base VHD name - disco.vhdx
10/11/2018 13:46:52 : [INFO ] Loading the cycle Data...
10/11/2018 13:46:52 : [INFO ] Loading the test data for VHDX-RESIZE-TO-BIGGER512
10/11/2018 13:46:52 : [INFO ] Loading the test data for VHDX-RESIZE-TO-BIGGER512
10/11/2018 13:55:28 : [INFO ] Checking background cleanup jobs..
10/11/2018 13:55:28 : [INFO ] Removed 0 context files.
10/11/2018 13:55:28 : [INFO ] Cycle Finished.. TC-33821
10/11/2018 13:55:28 : [INFO ]
Test Results Summary
ICA test run on 10/11/2018 13:46:52
VHD under test disco.vhdx
ARM Image under test  :  :  :
Total Executed TestCases         1 (        0 Pass,         1 Fail,         0 Abort)
Total Execution Time(dd:hh:mm) 0:0:8
XML file: TestConfiguration

#Sr. Test Name : Test Result : Test Duration (in minutes)
----------------------------------------------------
1. VHDX-RESIZE-TO-BIGGER512 : FAIL : 8.59


Logs can be found at .\TestResults\2018-11-10-19-16-51-6878


10/11/2018 13:55:28 : [INFO ] Creating 'HyperV-33821-buildlogs.zip' from '.\TestResults\2018-11-10-19-16-51-6878'
10/11/2018 13:55:29 : [INFO ] D:\Santosh\GitHub\LISAv2\HyperV-33821-buildlogs.zip created successfully.
10/11/2018 13:55:29 : [INFO ] Copied : .\report\report_TC-33821.xml --> .\report\report_TC-33821-junit.xml
10/11/2018 13:55:29 : [INFO ] Analysing results..
10/11/2018 13:55:29 : [INFO ] PASS  : 0
10/11/2018 13:55:29 : [INFO ] FAIL  : 1
10/11/2018 13:55:29 : [INFO ] ABORT : 0
10/11/2018 13:55:29 : [INFO ] LISAv2 exits with code: 1

2018-10-11 16:51 UTC, santoshx reviewed
Done

2018-10-11 16:51 UTC, santoshx commented on Testscripts/Linux/STOR_VHDXResize_PartitionDisk.sh
> +# permissions and limitations under the License.
You may need to shorten this License information. See other already merged .sh files.

2018-10-11 16:51 UTC, santoshx commented on Testscripts/Linux/STOR_VHDXResize_ReadWrite.sh
> +# permissions and limitations under the License.
Same here about License.

2018-10-11 16:51 UTC, santoshx commented on Testscripts/Windows/STOR_VHDXResize_Basic.ps1
> +    $ip = $AllVMData.PublicIP
Alignment issue, looks like tab is missing

2018-10-11 16:51 UTC, santoshx commented on XML/TestCases/FunctionalTests.xml
> -    </test>
Try to to change existing line of code

2018-10-12 03:19 UTC, prashantmhetar requested changes
Please modify these shell scripts as per the Lisav2 framework

2018-10-12 03:26 UTC, prashantmhetar commented on Testscripts/Linux/STOR_VHDXResize_ReadWrite.sh
> +ICA_TESTRUNNING="TestRunning"      # The test is running
Use utils.sh file for TEST status

2018-10-12 03:26 UTC, prashantmhetar commented on Testscripts/Linux/STOR_VHDXResize_PartitionDisk.sh
> +ICA_TESTRUNNING="TestRunning"      # The test is running
Use utils.sh for TEST status

2018-10-12 03:29 UTC, prashantmhetar commented on Testscripts/Windows/STOR_VHDXResize_Basic.ps1
> +
Check spaces in PS1 script. Run PSScriptAnalyser to resolve  line alignment

2018-10-12 03:30 UTC, prashantmhetar commented on Testscripts/Windows/STOR_VHDXResize_Basic.ps1
> +		    return "Skipped"
As we are using try-Block, throw should be used. 
return "Skipped" is not permissable

2018-10-12 03:30 UTC, prashantmhetar commented on Testscripts/Windows/STOR_VHDXResize_Basic.ps1
> +				return "Skipped"
same as above

2018-10-12 03:33 UTC, prashantmhetar commented on Testscripts/Windows/STOR_VHDXResize_Basic.ps1
> +		    return "FAIL"
Need to use throw

2018-10-12 03:33 UTC, prashantmhetar commented on Testscripts/Windows/STOR_VHDXResize_Basic.ps1
> +		    return "FAIL"
Why so many return "FAIL"

2018-10-12 03:40 UTC, prashantmhetar commented on Testscripts/Windows/STOR_VHDXResize_Basic.ps1
> +		RemoteCopy -uploadTo $ip -port $port -files $guest_script_path$guest_script -username $user -password $password -upload
Do we need to remote copy this script? Can it be part of XML file tag

2018-10-12 03:41 UTC, prashantmhetar commented on Testscripts/Windows/STOR_VHDXResize_Basic.ps1
> +			$guest_script = "STOR_VHDXResize_PartitionDiskOver2TB.sh"
Is STOR_VHDXResize_PartitionDiskOver2TB.sh already part of Lisav2 framework?

2018-10-12 03:42 UTC, prashantmhetar commented on Testscripts/Windows/STOR_VHDXResize_Basic.ps1
> +	} catch {
If return is used in try { } block do we need catch- finally?

2018-10-12 06:22 UTC, prashantmhetar reviewed
I can see test result is Failed. Please perform the testing.

2018-10-14 09:20 UTC, santoshx commented on Testscripts/Windows/STOR_VHDXResize_Basic.ps1
> +		    return "Skipped"
Done

2018-10-14 09:20 UTC, santoshx commented on Testscripts/Windows/STOR_VHDXResize_Basic.ps1
> +				return "Skipped"
Done

2018-10-14 09:21 UTC, santoshx commented on Testscripts/Windows/STOR_VHDXResize_Basic.ps1
> +			$guest_script = "STOR_VHDXResize_PartitionDiskOver2TB.sh"
Not needed in these test cases.

2018-10-14 09:21 UTC, santoshx commented on Testscripts/Windows/STOR_VHDXResize_Basic.ps1
> +	} catch {
Done

2018-10-14 18:29 UTC, santoshx commented
#Sr. Test Name : Test Result : Test Duration (in minutes)
----------------------------------------------------
1. VHDX-RESIZE-TO-BIGGER512 : PASS : 10.23
2. VHDX-RESIZE-TO-BIGGER4096 : PASS : 5.62


Logs can be found at .\TestResults\2018-14-10-23-42-36-3567


10/14/2018 18:28:33 : [INFO ] Creating 'HyperV-39635-buildlogs.zip' from '.\TestResults\2018-14-10-23-42-36-3567'
10/14/2018 18:28:33 : [INFO ] D:\Santosh\GitHub\LISAv2\HyperV-39635-buildlogs.zip created successfully.
10/14/2018 18:28:33 : [INFO ] Copied : .\report\report_TC-39635.xml --> .\report\report_TC-39635-junit.xml
10/14/2018 18:28:33 : [INFO ] Analysing results..
10/14/2018 18:28:33 : [INFO ] PASS  : 2
10/14/2018 18:28:33 : [INFO ] FAIL  : 0
10/14/2018 18:28:33 : [INFO ] ABORT : 0

2018-10-16 10:12 UTC, santoshx commented
#Sr. Test Name : Test Result : Test Duration (in minutes)
----------------------------------------------------
1. VHDX-RESIZE-TO-BIGGER512 : PASS : 9.59
2. VHDX-RESIZE-TO-BIGGER4096 : PASS : 6.19
3. VHDX-RESIZE-TO-BIGGER512-FIXED-IDE : PASS : 7.58
4. VHDX-RESIZE-TO-BIGGER512-DYNAMIC-IDE : PASS : 7.31
5. VHDX-RESIZE-TO-SMALLER512 : PASS : 6.08
6. VHDX-RESIZE-TO-SMALLER4096 : PASS : 11.92


Logs can be found at .\TestResults\2018-16-10-14-51-35-6425


10/16/2018 10:10:18 : [INFO ] Creating 'HyperV-22331-buildlogs.zip' from '.\TestResults\2018-16-10-14-51-35-6425'
10/16/2018 10:10:19 : [INFO ] D:\Santosh\GitHub\LISAv2\HyperV-22331-buildlogs.zip created successfully.
10/16/2018 10:10:19 : [INFO ] Copied : .\report\report_TC-22331.xml --> .\report\report_TC-22331-junit.xml
10/16/2018 10:10:19 : [INFO ] Analysing results..
10/16/2018 10:10:19 : [INFO ] PASS  : 6
10/16/2018 10:10:19 : [INFO ] FAIL  : 0
10/16/2018 10:10:19 : [INFO ] ABORT : 0
10/16/2018 10:10:19 : [INFO ] LISAv2 exits with code: 0

2018-10-16 11:13 UTC, merged